// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: plugin_manager.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Plugin_ListenerType int32

const (
	Plugin_Outbound Plugin_ListenerType = 0
	Plugin_Inbound  Plugin_ListenerType = 1
	Plugin_Gateway  Plugin_ListenerType = 2
)

var Plugin_ListenerType_name = map[int32]string{
	0: "Outbound",
	1: "Inbound",
	2: "Gateway",
}

var Plugin_ListenerType_value = map[string]int32{
	"Outbound": 0,
	"Inbound":  1,
	"Gateway":  2,
}

func (x Plugin_ListenerType) String() string {
	return proto.EnumName(Plugin_ListenerType_name, int32(x))
}

func (Plugin_ListenerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_58d89e785e3ecf0c, []int{1, 0}
}

type PluginManager struct {
	// Zero or more labels that indicate a specific set of pods/VMs whose
	// proxies should be configured to use these additional filters.  The
	// scope of label search is platform dependent. On Kubernetes, for
	// example, the scope includes pods running in all reachable
	// namespaces. Omitting the selector applies the filter to all proxies in
	// the mesh.
	WorkloadLabels map[string]string `protobuf:"bytes,1,rep,name=workload_labels,json=workloadLabels,proto3" json:"workload_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Plugin         []*Plugin         `protobuf:"bytes,2,rep,name=plugin,proto3" json:"plugin,omitempty"`
	// Names of gateways where the rule should be applied to. Gateway names
	// at the top of the VirtualService (if any) are overridden. The gateway
	// match is independent of sourceLabels.
	Gateways             []string `protobuf:"bytes,3,rep,name=gateways,proto3" json:"gateways,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginManager) Reset()         { *m = PluginManager{} }
func (m *PluginManager) String() string { return proto.CompactTextString(m) }
func (*PluginManager) ProtoMessage()    {}
func (*PluginManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_58d89e785e3ecf0c, []int{0}
}
func (m *PluginManager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginManager.Unmarshal(m, b)
}
func (m *PluginManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginManager.Marshal(b, m, deterministic)
}
func (m *PluginManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginManager.Merge(m, src)
}
func (m *PluginManager) XXX_Size() int {
	return xxx_messageInfo_PluginManager.Size(m)
}
func (m *PluginManager) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginManager.DiscardUnknown(m)
}

var xxx_messageInfo_PluginManager proto.InternalMessageInfo

func (m *PluginManager) GetWorkloadLabels() map[string]string {
	if m != nil {
		return m.WorkloadLabels
	}
	return nil
}

func (m *PluginManager) GetPlugin() []*Plugin {
	if m != nil {
		return m.Plugin
	}
	return nil
}

func (m *PluginManager) GetGateways() []string {
	if m != nil {
		return m.Gateways
	}
	return nil
}

type Plugin struct {
	Enable bool   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Deprecated
	Settings     *types.Struct       `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	ListenerType Plugin_ListenerType `protobuf:"varint,4,opt,name=listenerType,proto3,enum=slime.microservice.plugin.v1alpha1.Plugin_ListenerType" json:"listenerType,omitempty"`
	TypeUrl      string              `protobuf:"bytes,5,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// Types that are valid to be assigned to PluginSettings:
	//	*Plugin_Wasm
	//	*Plugin_Inline
	PluginSettings       isPlugin_PluginSettings `protobuf_oneof:"plugin_settings"`
	Port                 uint32                  `protobuf:"varint,8,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Plugin) Reset()         { *m = Plugin{} }
func (m *Plugin) String() string { return proto.CompactTextString(m) }
func (*Plugin) ProtoMessage()    {}
func (*Plugin) Descriptor() ([]byte, []int) {
	return fileDescriptor_58d89e785e3ecf0c, []int{1}
}
func (m *Plugin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plugin.Unmarshal(m, b)
}
func (m *Plugin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plugin.Marshal(b, m, deterministic)
}
func (m *Plugin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plugin.Merge(m, src)
}
func (m *Plugin) XXX_Size() int {
	return xxx_messageInfo_Plugin.Size(m)
}
func (m *Plugin) XXX_DiscardUnknown() {
	xxx_messageInfo_Plugin.DiscardUnknown(m)
}

var xxx_messageInfo_Plugin proto.InternalMessageInfo

type isPlugin_PluginSettings interface {
	isPlugin_PluginSettings()
}

type Plugin_Wasm struct {
	Wasm *Wasm `protobuf:"bytes,6,opt,name=wasm,proto3,oneof" json:"wasm,omitempty"`
}
type Plugin_Inline struct {
	Inline *Inline `protobuf:"bytes,7,opt,name=inline,proto3,oneof" json:"inline,omitempty"`
}

func (*Plugin_Wasm) isPlugin_PluginSettings()   {}
func (*Plugin_Inline) isPlugin_PluginSettings() {}

func (m *Plugin) GetPluginSettings() isPlugin_PluginSettings {
	if m != nil {
		return m.PluginSettings
	}
	return nil
}

func (m *Plugin) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Plugin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plugin) GetSettings() *types.Struct {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *Plugin) GetListenerType() Plugin_ListenerType {
	if m != nil {
		return m.ListenerType
	}
	return Plugin_Outbound
}

func (m *Plugin) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *Plugin) GetWasm() *Wasm {
	if x, ok := m.GetPluginSettings().(*Plugin_Wasm); ok {
		return x.Wasm
	}
	return nil
}

func (m *Plugin) GetInline() *Inline {
	if x, ok := m.GetPluginSettings().(*Plugin_Inline); ok {
		return x.Inline
	}
	return nil
}

func (m *Plugin) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Plugin) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Plugin_Wasm)(nil),
		(*Plugin_Inline)(nil),
	}
}

type Wasm struct {
	RootID               string        `protobuf:"bytes,1,opt,name=rootID,proto3" json:"rootID,omitempty"`
	FileName             string        `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Settings             *types.Struct `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Wasm) Reset()         { *m = Wasm{} }
func (m *Wasm) String() string { return proto.CompactTextString(m) }
func (*Wasm) ProtoMessage()    {}
func (*Wasm) Descriptor() ([]byte, []int) {
	return fileDescriptor_58d89e785e3ecf0c, []int{2}
}
func (m *Wasm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wasm.Unmarshal(m, b)
}
func (m *Wasm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wasm.Marshal(b, m, deterministic)
}
func (m *Wasm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wasm.Merge(m, src)
}
func (m *Wasm) XXX_Size() int {
	return xxx_messageInfo_Wasm.Size(m)
}
func (m *Wasm) XXX_DiscardUnknown() {
	xxx_messageInfo_Wasm.DiscardUnknown(m)
}

var xxx_messageInfo_Wasm proto.InternalMessageInfo

func (m *Wasm) GetRootID() string {
	if m != nil {
		return m.RootID
	}
	return ""
}

func (m *Wasm) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *Wasm) GetSettings() *types.Struct {
	if m != nil {
		return m.Settings
	}
	return nil
}

type Inline struct {
	Settings             *types.Struct `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Inline) Reset()         { *m = Inline{} }
func (m *Inline) String() string { return proto.CompactTextString(m) }
func (*Inline) ProtoMessage()    {}
func (*Inline) Descriptor() ([]byte, []int) {
	return fileDescriptor_58d89e785e3ecf0c, []int{3}
}
func (m *Inline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inline.Unmarshal(m, b)
}
func (m *Inline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inline.Marshal(b, m, deterministic)
}
func (m *Inline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inline.Merge(m, src)
}
func (m *Inline) XXX_Size() int {
	return xxx_messageInfo_Inline.Size(m)
}
func (m *Inline) XXX_DiscardUnknown() {
	xxx_messageInfo_Inline.DiscardUnknown(m)
}

var xxx_messageInfo_Inline proto.InternalMessageInfo

func (m *Inline) GetSettings() *types.Struct {
	if m != nil {
		return m.Settings
	}
	return nil
}

func init() {
	proto.RegisterEnum("slime.microservice.plugin.v1alpha1.Plugin_ListenerType", Plugin_ListenerType_name, Plugin_ListenerType_value)
	proto.RegisterType((*PluginManager)(nil), "slime.microservice.plugin.v1alpha1.PluginManager")
	proto.RegisterMapType((map[string]string)(nil), "slime.microservice.plugin.v1alpha1.PluginManager.WorkloadLabelsEntry")
	proto.RegisterType((*Plugin)(nil), "slime.microservice.plugin.v1alpha1.Plugin")
	proto.RegisterType((*Wasm)(nil), "slime.microservice.plugin.v1alpha1.Wasm")
	proto.RegisterType((*Inline)(nil), "slime.microservice.plugin.v1alpha1.Inline")
}

func init() { proto.RegisterFile("plugin_manager.proto", fileDescriptor_58d89e785e3ecf0c) }

var fileDescriptor_58d89e785e3ecf0c = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0xeb, 0x24, 0x75, 0xdc, 0x93, 0xb4, 0xcd, 0xb4, 0xb2, 0x79, 0x61, 0x17, 0xc1, 0x57,
	0xa6, 0x0c, 0x99, 0xa6, 0xb0, 0x8d, 0xc1, 0x06, 0x0b, 0x2d, 0x6b, 0xa0, 0xfb, 0x83, 0xb7, 0x51,
	0xd8, 0x2e, 0x82, 0x92, 0xa8, 0x9e, 0xa8, 0x2c, 0x19, 0x49, 0x4e, 0xc8, 0xeb, 0xec, 0x61, 0xf6,
	0x5c, 0xc3, 0x92, 0x93, 0x35, 0x30, 0x58, 0xd8, 0xdd, 0xf9, 0x84, 0x7e, 0xdf, 0x39, 0x3a, 0x9f,
	0x0d, 0x27, 0x05, 0x2f, 0x33, 0x26, 0x26, 0x39, 0x11, 0x24, 0xa3, 0x0a, 0x17, 0x4a, 0x1a, 0x89,
	0x22, 0xcd, 0x59, 0x4e, 0x71, 0xce, 0x66, 0x4a, 0x6a, 0xaa, 0x16, 0x6c, 0x46, 0xb1, 0xbb, 0x88,
	0x17, 0x67, 0x84, 0x17, 0x3f, 0xc8, 0x59, 0xff, 0x69, 0x26, 0x65, 0xc6, 0x69, 0x62, 0x89, 0x69,
	0x79, 0x9b, 0x68, 0xa3, 0xca, 0x99, 0x71, 0x0e, 0xd1, 0xcf, 0x06, 0x1c, 0x7e, 0xb2, 0xc4, 0x7b,
	0xe7, 0x8c, 0x04, 0x1c, 0x2f, 0xa5, 0xba, 0xe3, 0x92, 0xcc, 0x27, 0x9c, 0x4c, 0x29, 0xd7, 0xa1,
	0x37, 0x68, 0xc6, 0x9d, 0xe1, 0x25, 0xfe, 0x77, 0x37, 0xbc, 0xe5, 0x85, 0x6f, 0x6a, 0xa3, 0x6b,
	0xeb, 0x73, 0x29, 0x8c, 0x5a, 0xa5, 0x47, 0xcb, 0xad, 0x43, 0x34, 0x02, 0xdf, 0x99, 0x84, 0x0d,
	0xdb, 0xe6, 0x74, 0xf7, 0x36, 0x69, 0x4d, 0xa2, 0x3e, 0x04, 0x19, 0x31, 0x74, 0x49, 0x56, 0x3a,
	0x6c, 0x0e, 0x9a, 0xf1, 0x41, 0xba, 0xd1, 0xfd, 0xb7, 0xf0, 0xf0, 0x2f, 0x63, 0xa0, 0x1e, 0x34,
	0xef, 0xe8, 0x2a, 0xf4, 0x06, 0x5e, 0x7c, 0x90, 0x56, 0x25, 0x3a, 0x81, 0xfd, 0x05, 0xe1, 0x25,
	0x0d, 0x1b, 0xf6, 0xcc, 0x89, 0x57, 0x8d, 0x97, 0x5e, 0xf4, 0xab, 0x09, 0xbe, 0xeb, 0x88, 0x1e,
	0x81, 0x4f, 0x05, 0x99, 0x72, 0x6a, 0xc9, 0x20, 0xad, 0x15, 0x42, 0xd0, 0x12, 0x24, 0x5f, 0xb3,
	0xb6, 0x46, 0xe7, 0x10, 0x68, 0x6a, 0x0c, 0x13, 0x59, 0x35, 0x95, 0x17, 0x77, 0x86, 0x8f, 0xb1,
	0x0b, 0x03, 0xaf, 0xc3, 0xc0, 0x9f, 0x6d, 0x18, 0xe9, 0xe6, 0x22, 0xfa, 0x0e, 0x5d, 0xce, 0xb4,
	0xa1, 0x82, 0xaa, 0x2f, 0xab, 0x82, 0x86, 0xad, 0x81, 0x17, 0x1f, 0x0d, 0x5f, 0xec, 0xbe, 0x14,
	0x7c, 0x7d, 0x0f, 0x4f, 0xb7, 0xcc, 0xd0, 0x13, 0x08, 0xcc, 0xaa, 0xa0, 0x93, 0x52, 0xf1, 0x70,
	0xdf, 0x4e, 0xda, 0xae, 0xf4, 0x57, 0xc5, 0xd1, 0x1b, 0x68, 0x2d, 0x89, 0xce, 0x43, 0xdf, 0x0e,
	0x1a, 0xef, 0xd2, 0xef, 0x86, 0xe8, 0xfc, 0x6a, 0x2f, 0xb5, 0x1c, 0xba, 0x00, 0x9f, 0x09, 0xce,
	0x04, 0x0d, 0xdb, 0xd6, 0x61, 0xa7, 0x18, 0xc7, 0x96, 0xb8, 0xda, 0x4b, 0x6b, 0xb6, 0x5a, 0x63,
	0x21, 0x95, 0x09, 0x83, 0x81, 0x17, 0x1f, 0xa6, 0xb6, 0x8e, 0x9e, 0x43, 0xf7, 0xfe, 0x93, 0x50,
	0x17, 0x82, 0x8f, 0xa5, 0x99, 0xca, 0x52, 0xcc, 0x7b, 0x7b, 0xa8, 0x03, 0xed, 0xb1, 0x70, 0xc2,
	0xab, 0xc4, 0x3b, 0x97, 0x7b, 0xaf, 0x31, 0x7a, 0x00, 0xc7, 0xf5, 0x4f, 0xb3, 0x5e, 0x6e, 0x24,
	0xa1, 0x55, 0x0d, 0x5d, 0xa5, 0xa8, 0xa4, 0x34, 0xe3, 0x8b, 0x3a, 0xff, 0x5a, 0x55, 0xdf, 0xd1,
	0x2d, 0xe3, 0xf4, 0xc3, 0x9f, 0x24, 0x37, 0xfa, 0xbf, 0xd2, 0x8c, 0x5e, 0x83, 0xef, 0xde, 0xb8,
	0x85, 0x7b, 0x3b, 0xe2, 0xa3, 0x67, 0xdf, 0x4e, 0xdd, 0x16, 0x99, 0x4c, 0x6c, 0x91, 0xe4, 0x72,
	0x5e, 0x72, 0xaa, 0x13, 0xf7, 0xb2, 0x84, 0x14, 0x2c, 0x59, 0x6f, 0x73, 0xea, 0x5b, 0xa3, 0xf3,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x99, 0x26, 0xe3, 0x2c, 0x04, 0x00, 0x00,
}
